spring:
  application:
    name: CSVTest

  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  profiles:
    active: local

---
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  profiles: local

  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres